### ISSUE TITLE
如何处理同一类型不同布局样式？

### ISSUE THREAD

**Issue by FynnJason** [F1ReKing/StatusLayout#2]
例如在数据为空时，需要显示空布局，但是空布局的图片可能时多种情况，例如历史记录中，没有数据显示无历史数据的图片，收藏界面中，没有数据时显示无收藏数据的图片，虽然都是无数据情况，但是显示的图片是不同的

**Comment by GeekBugs** [comment]
> 例如在数据为空时，需要显示空布局，但是空布局的图片可能时多种情况，例如历史记录中，没有数据显示无历史数据的图片，收藏界面中，没有数据时显示无收藏数据的图片，虽然都是无数据情况，但是显示的图片是不同的

可以构建时加载不同空布局，api中有提供
