### ISSUE TITLE
一个小建议啊

### ISSUE THREAD

**Issue by safaribest** [F1ReKing/StatusLayout#3]
如果可以把 多个状态 布局 通过builder传入就更灵活了，国内产品 ui 各种各样。。。

**Comment by GeekBugs** [comment]
> 如果可以把 多个状态 布局 通过builder传入就更灵活了，国内产品 ui 各种各样。。。

这个有考虑过，但最终还是通过不同的接口进行设置不同的状态布局这样会比较好
